### ISSUE TITLE
Creating an xcframework doesn't work when Lottie is a dependency

### ISSUE THREAD

**Issue by darecki** [unsignedapps/swift-create-xcframework#14]
I can't create an xcframework when Lottie is a dependency. Please note, that exchanging Lottie with for example RxSwift makes it work. Do you have any idea what could be an issue and how to resolve it?

**swift-create-xcframework version:** `1.2.0` 
**Swift version:** 
Apple Swift version 5.3 (swiftlang-1200.0.16.13 clang-1200.0.22.25)
Target: x86_64-apple-darwin19.5.0
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/lldb "--repl=-enable-objc-interop -stack-check -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.16.sdk -color-diagnostics -target-sdk-version 10.16"

**Environment:** Xcode 12 beta 2 and macOS Catalina 10.15.5

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

1. Create a new package, add Lottie as a dependency as described here: https://github.com/airbnb/lottie-ios#swift-package-manager (but with // swift-tools-version:5.3)
2. Call `swift create-xcframework --platform ios`

### Expected behavior

An xcframework is created properly

### Actual behavior

** BUILD FAILED **

The following build commands failed:
	Ld <path_to_package>/<package_name>/build/<package_name>.build/Release-iphoneos/Lottie.build/Objects-normal/armv7/Binary/Lottie normal armv7
	Ld <path_to_package>/<package_name>/build/<package_name>.build/Release-iphoneos/<package_name>.build/Objects-normal/arm64/Binary/<package_name> normal arm64
	Ld <path_to_package>/<package_name>/build/<package_name>.build/Release-iphoneos/<package_name>.build/Objects-normal/armv7/Binary/<package_name> normal armv7
(3 failures)
Error: xcodebuild exited with a non-zero code: 65

**Comment by bok-** [comment]
Hi @darecki, apologies for the delayed reply. I've tested with this the new 1.3.0 release and compiling Lottie appears to be working correctly now
