### ISSUE TITLE
Error: artifact not found for target 'xxxx' (binaryTarget not supported ?)

### ISSUE THREAD

**Issue by quentinfasquel** [unsignedapps/swift-create-xcframework#15]
The error `Error: artifact not found for target 'xxxx'` is thrown immediately when using the command-line `swift-create-xcframework`.

**swift-create-xcframework version:** `master` branch
**Swift version:** Apple Swift version 5.3 (swiftlang-1200.0.16.13 clang-1200.0.22.25)
**Environment:** Xcode 12 beta 2, macOS 10.15.5

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

From the root directory of my swift package, executing `swift create-xcframework` results in the error `Error: artifact not found for target 'xxxx'`, where target is a binaryTarget.

```
...
targets: [
        .binaryTarget(
            name: "xxxx",
            url: "https://my_own_url_which_is_reachable/xxxx.xcframework.zip",
            checksum: "...some_checksum_that_is_correct..."),
         .target(
            name: "MyTarget",
            dependencies: ["xxxx"],
...
```

**Comment by bok-** [comment]
Thanks @quentinfasquel, apologies for the delayed reply. I haven't actually tested building XCFrameworks with binary targets. I'll see what changes we need to make to support them

**Comment by apps4everyone** [comment]
Hey, some news here? getting `Error: Xcode project generation is not supported by Swift Package Manager for packages that contain binary targets.These binary targets were detected...`. Is there something I could contribute to add `binary targets` support? Or is this a SPM limitation? Would be great to get a hint to work on this? Where to start? thx

**Comment by dmn-star** [comment]
+ 1 Error: Xcode project generation is not supported by Swift Package Manager for packages that contain binary targets.These binary targets were detected: xxxx.

**Comment by mohamed-3amer** [comment]
reopen

**Comment by engineearemotetechnologiessl** [comment]
Hi!
I'm getting Error: Xcode project generation is not supported by Swift Package Manager for packages that contain binary targets.These binary targets were detected....

Is somebody working on it?

**Comment by mosamer** [comment]
I believe this error has been introduced intentionally in this [pull request](https://github.com/unsignedapps/swift-create-xcframework/pull/32) to avoid the thrown [`InternalError`](https://github.com/apple/swift-package-manager/blob/c6e40adbfc78acc60ca464ae482b56442f9f34f4/Sources/Xcodeproj/pbxproj.swift#L398) from Apple's `SwiftPM` Xcode project generation. 

FWIW, this whole system has been [removed](https://github.com/apple/swift-package-manager/pull/5748/files) which means we need to migrate to either the more modern [PIF Builder](https://github.com/apple/swift-package-manager/blob/main/Sources/XCBuildSupport/PIFBuilder.swift) or another Xcode project generation tool such as [tuist/xcodeproj](https://github.com/tuist/xcodeproj). I'd be happy to help with this effort if needed :)

**Comment by minuscorp** [comment]
Any advance or solution into this issue? projects with binary targets are still not available
