### ISSUE TITLE
How to compile the project?

### ISSUE THREAD

**Issue by srdanrasic** [unsignedapps/swift-create-xcframework#17]
Hey @bok- 

First of all, thank you for this amazing tool! I have a problem building a target that has binary dependencies. I would like to debug this problem and fix it myself, but I can't get Xcode to resolve swift-create-xcframework dependencies. 

I tried checking out the master branch and then opening the package with both Xcode 11.7 and Xcode 12, but both of them fail to resolve dependencies. 

This is the error I get:

```
terminated(128): PATH=/Applications/Xcode_12.0.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin MallocNanoZone=0 HOME=/Users/srdan TMPDIR=/var/folders/3_/7hcdd_mn21966btxlssqks7r0000gn/T/ XPC_SERVICE_NAME=com.apple.dt.Xcode.77560 USER=srdan CA_ASSERT_MAIN_THREAD_TRANSACTIONS=1 LD_LIBRARY_PATH=/Applications/Xcode_11.7.app/Contents/Developer/../SharedFrameworks/ __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x2 SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.a8F4LHWIhW/Listeners LOGNAME=srdan CA_DEBUG_TRANSACTIONS=1 XPC_FLAGS=0x0 SHELL=/bin/zsh /Applications/Xcode_12.0.app/Contents/Developer/usr/bin/git -C /Users/srdan/Library/Developer/Xcode/DerivedData/swift-create-xcframework-fjrpprlxyvlvtjejjchsftytutaf/SourcePackages/repositories/swift-llbuild-0f2964f9 rev-parse --verify 'master^{commit}' output:

fatal: Needed a single revision
```

Is there anything you could do to help me get this project to compile? 

Thank you

**Comment by bok-** [comment]
Hi @srdanrasic, thanks for filing an issue. It looks like the SwiftPM team updated their `release/5.3` branch and it ended up having conflicts with other items. Version 1.3.0 should fix this issue.
