### ISSUE TITLE
dSYM support

### ISSUE THREAD

**Issue by dalu93** [unsignedapps/swift-create-xcframework#19]
Hi,

By simply running `swift-create-xcframework` command, the `.xcframework` is created successfully for my package and I appreciate it.
But a very important part of using packages in iOS/MacOS apps is to be able to debug possible crashes and the dSYMs are not included: from some Apple Forum discussions, the `xcodebuild` command should support a flag for generating such files together with the xcframework file.

More info [here](https://developer.apple.com/forums/thread/655768)

Would it be possible to wrap the flag as well and bundle the dSYMs together with the framework, please?

**Comment by bok-** [comment]
Hi @dalu93, thanks for the info! I wasn't aware that the `-debug-symbols` option was added. I'll see if we can fit it into the 1.3 release

**Comment by bok-** [comment]
I've raised an initial PR to include dSYM and BCSymbolMap files in the compiled XCFrameworks, but it will take me half a day before I'm able to run through enough test cases to ensure it works correctly for the different variants of Xcode and available platforms.

@dalu93 would you be able to give PR #23 a try to see if it works for your use case?
