### ISSUE TITLE
QUESTION: Should it be recursive?

### ISSUE THREAD

**Issue by ryanbooker** [unsignedapps/swift-create-xcframework#2]
i.e. If Package A depends on Package B. What should happen? At the moment it appears to build Package A as is, and assume Package B will be built independently and added along side it in the including app. Is this correct?

**Comment by bok-** [comment]
@ryanbooker that's correct. Much like Swift Binary Target support we don't attempt to solve dependencies as that would be a large problem to undertake.

We do support building your dependencies directly though – the SwiftPM generated xcproject bundle includes targets for everything in the package graph, so you can include them in your build list: `swift create-xcframework --list-products` will show you everything that is available to be built.

Maybe we should add in a `--build-all` option as well?

Apologies for the delayed reply!
