### ISSUE TITLE
[BUG] Unable to find a destination matching macCatalyst

### ISSUE THREAD

**Issue by fermoya** [unsignedapps/swift-create-xcframework#27]
Hi, when I pass the argument `--platform maccatalyst` in the terminal or in the GitHub Action, I get the following error:
```bash
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/fernando.moyaderivas/Documents/Playgrounds/SwiftUIPager-ssh/.build/swift-create-xcframework/SwiftUIPager.xcodeproj -configuration Release -archivePath /Users/fernando.moyaderivas/Documents/Playgrounds/SwiftUIPager-ssh/.build/swift-create-xcframework/build/SwiftUIPager/maccatalyst.xcarchive -destination "platform=macOS,variant=Mac Catalyst" BUILD_DIR=/Users/fernando.moyaderivas/Documents/Playgrounds/SwiftUIPager-ssh/.build/swift-create-xcframework/build SKIP_INSTALL=NO SUPPORTS_MACCATALYST=YES -scheme SwiftUIPager archive

User defaults from command line:
    IDEArchivePathOverride = /Users/fernando.moyaderivas/Documents/Playgrounds/SwiftUIPager-ssh/.build/swift-create-xcframework/build/SwiftUIPager/maccatalyst.xcarchive

Build settings from command line:
    BUILD_DIR = /Users/fernando.moyaderivas/Documents/Playgrounds/SwiftUIPager-ssh/.build/swift-create-xcframework/build
    SKIP_INSTALL = NO
    SUPPORTS_MACCATALYST = YES

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:macOS, variant:Mac Catalyst }
```
You can find my `Package.swift` [here](https://github.com/fermoya/SwiftUIPager/blob/develop/Package.swift)

**swift-create-xcframework version:** 
`1.3.0` and `master`
**Swift version:**
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
Target: x86_64-apple-darwin19.5.0
**Environment:** 
Xcode 12.0.1
macOS 10.15.5

### Checklist
- [✓] If possible, I've reproduced the issue using the `master` branch of this package
- [✓] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

Run `swift create-xcframework --platform maccatalyst` in your `Package.swift` folder.

### Expected behavior

Archive macCatalyst

### Actual behavior

Error archiving macCatalyst

**Comment by fermoya** [comment]
I just tried with Xcode 12.1 and same result

**Comment by 3a4oT** [comment]
I have the same issue
