### ISSUE TITLE
module 'XXX' has a minimum deployment target of iOS 14.4

### ISSUE THREAD

**Issue by fritzfr** [unsignedapps/swift-create-xcframework#36]
I have a swift package with multiple dependencies, from which I want to build a xcframework using this tool.
One of the dependencies is SwCrypt (https://github.com/soyersoyer/SwCrypt).

In the Package.swift file I declared it like this:

```swift
platforms: [
	.macOS(.v10_15), .iOS(.v11)
],
dependencies: [
	.package(url: "https://github.com/soyersoyer/SwCrypt.git", from: "5.1.4")
],
```

The problem is that when running `swift create-xcframework`, it fails with the following:

> /Users/myUsername/Desktop/fts/NetService/MyPackage/Sources/MyPackage/MyPackage.swift:9:8: error: compiling for iOS 11.0, but module 'SwCrypt' has a minimum deployment target of iOS 14.4: /Users/myUsername/Desktop/fts/NetService/MyPackage/.build/swift-create-xcframework/build/Release-iphoneos/SwCrypt.framework/Modules/SwCrypt.swiftmodule/arm64-apple-ios.swiftmodule
import SwCrypt
            ^

I don't understand this error, as SwCrypt does not seem to declare iOS 14.4 as minimum deployment anywhere. In addition, I can include SwCrypt into a different iOS app project with minimum set to iOS 11, and it will compile of course.

**swift-create-xcframework version:** master branch from today
**Swift version:** Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: arm64-apple-darwin20.3.0
**Environment:** Version 12.4 (12D4e), macOS 11.2.1 (M1 Macbook)

### Checklist
- [X] If possible, I've reproduced the issue using the `master` branch of this package
- [X] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

1. Create a new Swift Package
2. Add the SwCrypt dependency as mentioned above into the Package.swift file
3. `import SwCrypt` in some Swift file
4. Declare iOS 11 as platform in Package.swift
5. Try to run `swift-create-xcframework`

### Expected behavior

It should compile.

### Actual behavior

Described above.

**Comment by bok-** [comment]
Hi @fritzfr,

This is an issue with SwiftPM's Xcode project generation. You can check this by running `swift package generate-xcodeproj` and trying to build the resultant project.

Fortunately, or unfortunately, depending on how you see these things, enabling `BUILD_LIBRARY_FOR_DISTRIBUTION` tends to mess with minimum deployment settings on the targets it is enabled on.

So you can get around this by including SwCrypt in the list of targets to build, eg:

`swift create-xcframework <MyPackageProduct> SwCrypt`

This has the added bonus of building `SwCrypt.xcframework`, which you would need to be able to distribute your package anyway.

**Comment by fritzfr** [comment]
@bok- Thanks for the quick reply. I'm very new to XCode's toolchain. Maybe you can help me understand a few things.
As described, I'm building a Module, let's say "MyModule". It depends on SwCrypt. My goal is to create a binary (in the form of xcframework), which I then want to distribute as a swift package.

If I understand you correctly, I would need to create an xcframework for "MyModule" and "SwCrypt". How can I then combine both of them into a Swift Package? It seems like a binaryTarget needs to be declared in the Package.swift of that final Swift Package, e.g.:

```
.binaryTarget(name: "MyModule", path: "./Sources/MyModule.xcframework"),
```

Would I need another binaryTarget for SwCrypt, or can this even be accomplished?
