### ISSUE TITLE
Failed to import created xcframework

### ISSUE THREAD

**Issue by nixzhu** [unsignedapps/swift-create-xcframework#39]
**swift-create-xcframework version:** 1.3.0
**Swift version:**
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.3.0
**Environment:** Xcode 12.4 and macOS Big Sur 11.2.3

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

1. git clone https://github.com/minsOne/KakaoSDK-SwiftPM.git
2. cd KakaoSDK-SwiftPM
3. swift create-xcframework KakaoSDKCommon Alamofire DynamicCodable --platform iOS
4. Drag Alamofire.xcframework, DynamicCodable.xcframework, KakaoSDKCommon.xcframework to a new project
5. import KakaoSDKCommon in AppDelegate.swift
6. build

### Expected behavior

Import success and built

### Actual behavior

Build failed

<img width="1503" alt="build-failed" src="https://user-images.githubusercontent.com/435208/110917689-26b83f80-8355-11eb-96e5-e5b87cf6b01e.png">

**Comment by Fab1n** [comment]
Please help here. I have the same problem!

**Comment by apps4everyone** [comment]
Also had some troubles with e.g. `Alamofire` using `swift create-xcframework`. I think the created `xcframework` doesn't contain debug support? (BCSymbolMaps & dSYMs). If I use `carthage update --use-xcframeworks --no-use-binaries` with `github "Alamofire/Alamofire"` this is created and work's for me:

<img width="295" alt="Screenshot 2021-05-02 at 11 29 16" src="https://user-images.githubusercontent.com/1915802/116808537-a2569180-ab39-11eb-8669-06ca7e7cfb29.png">

**Comment by apps4everyone** [comment]
Another possible issue: `BUILD_LIBRARIES_FOR_DISTRIBUTION=YES` is missing next to `SKIP_INSTALL=NO`.

https://github.com/unsignedapps/swift-create-xcframework/blob/87f07d0a776eda0078927b3e2d852d9695c464b0/Sources/CreateXCFramework/XcodeBuilder.swift#L115

**Comment by tackgyu** [comment]
It happened to our projects when the framework contains a symbol having the same name as the name of output framework. Workaround is that you change the name of that type.

And it does not reproduce when using Carthage, hope it helps fixing the issue.
