### ISSUE TITLE
SPM defined Build Settings are not properly generated in xcodeproj

### ISSUE THREAD

**Issue by mhays118** [unsignedapps/swift-create-xcframework#49]
When defining build settings in the `Package.swift` file, it appears that the generated XcodeProject file does not respect the expected (and documented) behavior of `BuildSettingCondition`. 

If you add the following code:
```swift
.define("ENABLE_FEATURE_A")
```
Then, according to [Apples's Documentation on BuildSettingCondition](https://developer.apple.com/documentation/swift_packages/buildsettingcondition), this should apply to all platforms and build configurations.

This does not happen, instead the created xcodeproj only enables the build setting for DEBUG. 

**swift-create-xcframework version:** `master` branch
**Swift version:** Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
Target: x86_64-apple-darwin20.6.0
**Environment:** Xcode Version 12.5.1 (12E507), MacOS 11.5 (20G71)
**Source Code of test project:** [TestMacroDefinition.zip](https://github.com/unsignedapps/swift-create-xcframework/files/6901967/TestMacroDefinition.zip)

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

To reproduce, create a new Swift Package, set the following as the `Package.swift`:

```swift
import PackageDescription

let featureFlags: [SwiftSetting] = [
	  .define("ENABLE_FEATURE_A"),
    .define("ENABLE_FEATURE_B", .when(platforms: nil, configuration: .release))
]

let package = Package(
    name: "TestMacroDefinition",
    products: [
        .library(
            name: "TestMacroDefinition",
            targets: ["TestMacroDefinition"]),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "TestMacroDefinition",
            dependencies: [],
            swiftSettings: featureFlags + [.define("RELEASE", .when(platforms: nil, configuration: .release))]
        )
    ]
)
```

Then, in the one piece of source code in the library, replace it with this:

```swift
struct TestMacroDefinition {
    var text = "Hello, World!"

    #if ENABLE_FEATURE_A
    #if RELEASE
    #error("FEATURE A ENABLED")
    #endif
    #endif
}
```

With this, the library should fail to build if `ENABLE_FEATURE_A` is set and `RELEASE` is also set. 

In Xcode, if you go to Product -> Archive, this will (correctly) fail to build. 

Also, if you add a script to the directory of `build.sh` and add the following:

```bash
# iOS devices
xcodebuild archive \
    -scheme TestMacroDefinition \
    -archivePath "archives/TestMacroDefinition-iOS.xcarchive" \
    -destination "generic/platform=iOS" \
    -sdk iphoneos \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
# iOS simulators
xcodebuild archive \
    -scheme TestMacroDefinition \
    -archivePath "archives/TestMacroDefinition-iOS-simulator.xcarchive" \
    -destination "generic/platform=iOS Simulator" \
    -sdk iphonesimulator \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild -create-xcframework \
    -framework "archives/TestMacroDefinition-iOS.xcarchive/Products/Library/Frameworks/TestMacroDefinition.framework" \
    -framework "archives/TestMacroDefinition-iOS-simulator.xcarchive/Products/Library/Frameworks/TestMacroDefinition.framework" \
    -output "TestMacroDefinition.xcframework"
```

and run the following in your terminal:
```bash
sh build.sh
```
It also (correctly) fails to build.

When running this with swift-create-xcframework, this however, does build (incorrectly). 

I have cloned the main branch of `swift-create-xcframework` and debugged this. It appears that the created .xcodeproj file for the above has an issue. 

![image](https://user-images.githubusercontent.com/12106180/127525729-30261aac-ce10-45ec-b0dc-28a560e58efc.png)
![image](https://user-images.githubusercontent.com/12106180/127525872-a98d3d78-9226-45b6-a552-64be1bec022a.png)

If you'll notice, for release, it does not have an `$(inherited)`, I believe this is making it not take the `ENABLE_FEATURE_A` from common.

This can be seen in the xcodeproject.
![image](https://user-images.githubusercontent.com/12106180/127526194-e90275d1-46df-4a55-8ede-a8a91a87e06d.png)
![image](https://user-images.githubusercontent.com/12106180/127526215-6226ea6b-f0c2-4ab1-8406-bc79847bcf40.png)

This also appears the same if I directly run `swift package generate-xcodeproj` in my terminal for this swift package.

### Expected behavior

swift-create-xcframework should fail to build.

### Actual behavior

swift-create-xcframework successfully builds (incorrectly).

**Comment by mhays118** [comment]
This seems to be an issue not with swift-create-xcframework, but with `swift package generate-xcodeproj`. 

Perhaps an `$(inherited)` should be added for release configs somewhere in the code?

Alternatively, it looks to me like this library may not even need to create xcodeproj files to make the XCFramework. As in the Steps to Reproduce, there are ways of build the project without using xcodeproj. Are there any edge cases where the xcodeproj is required?

**Comment by bok-** [comment]
Hi @mhays118. As you've noted, `xcodebuild` has native support for building packages directly now, so we've got a refactor in progress that moves the existing behaviour to a `--legacy` flag for backwards compatibility. You do lose being able to build your entire package and its dependencies in a single command and building non-`.dynamic` products, but as SwiftPM will one day drop support for xcodeproj generation this will be the way of the future.
