### ISSUE TITLE
Version Is Always 1.4.0

### ISSUE THREAD

**Issue by VaslD** [unsignedapps/swift-create-xcframework#60]
Replace this paragraph with a short description of the incorrect incorrect behavior. If this is a regression, please note the last version that the behavior was correct in addition to your current version. Please also include any information you have about the environment as this tool is very sensitive to Xcode and SDK versions.

**swift-create-xcframework version:** `master`
**Swift version:** 5.5
**Environment:** macOS 12.0.1; Xcode 13.1

THIS HAPPENS REGARDLESS OF TOOLCHAIN VERSIONS!

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

Replace this paragraph with an explanation of how to reproduce the incorrect behavior. This could include a code listing for a reduced version of your command, or a link to the code that is exhibiting the issue.

`swift create-xcframework --version`

### Expected behavior

Describe what you expect to happen.

With the latest version, prints `2.1.0`.

### Actual behavior

Describe or copy/paste the behavior you observe.

`1.4.0` because of https://github.com/unsignedapps/swift-create-xcframework/blob/a8376e964c5e29dae0290f53c3aa865bb5f34d00/Sources/CreateXCFramework/Command.swift#L30

-----

This is so rudimentary. I did not realize it was a *swift-create-xcframework* bug and wasted half an hour messing with Mint to get "the latest" version.

**Comment by antranapp** [comment]
I believe the issue is because the tag has the format `v2.1.0`. It would work if we change the format for the tags to `2.1.0`
