### ISSUE TITLE
Build swift-nio, swift-grpc and others.

### ISSUE THREAD

**Issue by bimawa** [unsignedapps/swift-create-xcframework#66]
Found this repo while research how to create xcframework for swift-grpc. And detect issue with inclined methods. 
How did you solve this issue?
![CleanShot 2022-05-11 at 13 16 07](https://user-images.githubusercontent.com/1393809/167802307-f6a3df76-06be-4684-891a-de69e7214b06.png)

**Comment by bok-** [comment]
Hi @bimawa, unfortunately to get swift-nio and grpc-swift and friends to compile as XCFrameworks you need to disable Library Evolution on them by stripping it out before trying to build:

```bash
swift package reset
swift package resolve
find \
    .build/checkouts/swift-nio .build/checkouts/swift-nio-ssl .build/checkouts/swift-nio-http2 .build/checkouts/grpc-swift \
    -type f \
    -name '*.swift' \
    -exec sed -i '' -e 's/@inlinable//g' -e 's/@usableFromInline//g' {} +
```

This does mean there will be a small performance penalty as many methods will no longer be `@inlinable`, but that's the unfortunate price you need to pay to get this to work.

**Comment by bimawa** [comment]
Thanks! 
also received answer from guys: https://github.com/apple/swift-nio/issues/2106#issuecomment-1123340953

**Comment by bimawa** [comment]
@bok- sorry to disturb, but maybe you met with this issue? 
![CleanShot 2022-05-12 at 12 46 42](https://user-images.githubusercontent.com/1393809/168019212-256defbc-3090-4e52-934b-6b2bfc7179c6.png)
