### ISSUE TITLE
Support use swift-create-xcframework as Swift Library

### ISSUE THREAD

**Issue by 0xWOF** [unsignedapps/swift-create-xcframework#71]
Hello, thank you for creating awesome tool.

I'm software engineer on developing some ios sdk. And I planning to migrate xcode project to swift package and use swift-create-xcframework.
But I should notify to all of team members to install swift-create-xcframework to build xcframework on local machine.
It is not hard to do. But it can lead some miss communication.
So I think if I can use swift-create-xcframework as swift library, then I can use it without explicit install.

I think this feature not only solve my use case, but also give users more possibilities.

**Example:**
sdk project have below directories
```
SDK
- Package // library swift package of SDK
    - Source/...
    - Test/...
    - Package.swift
- Script // executable swift package of build script
    - Source
        - Build.swift
        - Main.swift
    - Package.swift // depend on swift-create-xcframework
```
and Build.swift have below code
```swift
import CreateXCFramework

CreateXCFramework.create(project: "path")
```
then I can build sdk with below command (swift package automatically download swift-create-xcframework)
```zsh
cd Script
swift run
```

**Comment by hectormatos2011** [comment]
This could be interesting as a Swift Package Plugin as well. Would allow teams to perform any preprocessing in a Swift script before calling `createXCFramework(project: "path")`

**Comment by bok-** [comment]
This is not something I am likely to get to anytime soon, but I would welcome any pull requests that added this functionality.

**Comment by hectormatos2011** [comment]
I actually got this working in a swift plugin of my own! When I get some time I’ll submit a PR for it that supports it as a swift package plug-in as well as a framework. This is a great package @bok- 

as it stands, you can bring this package in as a package dependency and make the executable target a dependency in a local swift package plug-in and then call it through plugin.swift without having to install the tool through other means
