### ISSUE TITLE
Error: Invalid product/target product but listed in available products

### ISSUE THREAD

**Issue by philprime** [unsignedapps/swift-create-xcframework#82]
I am using this tool as a github-action for my package [[Cabinet](https://github.com/](https://github.com/philprime/Cabinet) but it fails to find a product which is listed in the available products.
The product in question is a library which only combines other targets, see `Package.swift`

**swift-create-xcframework version:** `2.3.0`
**Swift version:** 
```
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0
```
**Environment:** 
Xcode 14.0.1
macOS 12.6
xcode-select version 2395.

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [X] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

1. Clone the repository:
```console
git clone https://github.com/philprime/Cabinet
```
2. Run the command:
```console
swift-create-xcframework
```
4. Inspect the error:
```console
debug: evaluating manifest for 'cabinet' v. unknown
debug: evaluating manifest for 'flow' v. 1.0.0
debug: evaluating manifest for 'cabinet' v. unknown
Error: Invalid product/target name(s):
    Cabinet

Available Cabinet products:
    Cabinet
    CabinetCoding
    CabinetCollections
    CabinetCrypto
    CabinetFoundation
    CabinetPartialTypes
    CabinetPropertyWrappers
    CabinetSwiftUI

Additional available targets:
    CabinetCore
    Flow
Usage: command [<options>] [<products> ...]
  See 'command --help' for more information.
```

### Expected behavior

It should build the frameworks

### Actual behavior

The target is not found and it throws an error, but also lists the target name in the list `Available Cabinet products`

**Comment by philprime** [comment]
still relevant

**Comment by philprime** [comment]
still relevant

**Comment by matteocrippa** [comment]
@philprime fyi seems an expected behaviour, checking the [code](https://github.com/unsignedapps/swift-create-xcframework/blob/main/Sources/CreateXCFramework/PackageInfo.swift#L191) you cannot have target(s) with the same name of the package "Cabinet"

**Comment by philprime** [comment]
@matteocrippa do we know why this exclusion is built-in?

**Comment by matteocrippa** [comment]
I was facing the same issue and started to dig down and discovered that trigger.
I can think that issue is from an old version of xCode, not sure if it's relevant still, but I recall some times ago it was generating xcframework with the wrong naming like "Cabinet.Cabinet" and imports were totally broken.

**Comment by philprime** [comment]
Maybe @bok- can give us some further insights before fork and pull-request to revert the exclusion
