### ISSUE TITLE
Mergable Library Support

### ISSUE THREAD

**Issue by spookyd** [unsignedapps/swift-create-xcframework#92]
First of all love this project. Thank you for creating this 😄 

[Mergable libraries](https://developer.apple.com/documentation/xcode/build-settings-reference#Build-Mergeable-Library) were announced in WWDC. This seems like a beautiful complement to this library.

What I am thinking is having the ability to pass in a flag that would eject all modules of a package as mergable frameworks. Taking it a step further the merged binaries could be merged into a container "merged" xcframework. This merged framework could additionally be specified as a mergable framework.

Any objections to adding support for these? Happy to contribute as well.

**Comment by osrufung** [comment]
Could be really nice! the problem now is that the xcodeproj dependency from SPM has been removed in Swift 5.9 and this project depends on the `-generate-xcodeproj` option which has been removed.

**Comment by spookyd** [comment]
Oh yeah bummer. Perhaps this project could simply reimplement the `Xcodeproj` [related code](https://github.com/apple/swift-package-manager/tree/release/5.7/Sources/Xcodeproj) from the pinned SPM version, `release/5.7` 🤔.

**Comment by osrufung** [comment]
exactly, this is what https://github.com/giginet/Scipio has done, but that´s still a project in development. I guess this shouldn´t be too hard to do.
